#:schema node_modules/wrangler/config-schema.json
name = "task-manager-app"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "tasks-db"
database_id = "128a5cf7-4d07-4d5f-b826-f6a930bfba6f"
migrations_dir = "drizzle/migrations"
